### Data numericalization

In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('test_cleaned.csv')

In [3]:
df.head()

Age Gender         Country self_employed family_history no_employees  \
0   25      M   United States            No            Yes         6-25   
1   42      M   United States            No            Yes         6-25   
2   34      M   United States            No            Yes      100-500   
3   26      F   United States            No             No       26-100   
4   35      M  United Kingdom            No            Yes          1-5   

  remote_work tech_company    benefits care_options  ...   anonymity  \
0         Yes          Yes         Yes          Yes  ...         Yes   
1         Yes          Yes  Don't know           No  ...  Don't know   
2          No          Yes         Yes          Yes  ...         Yes   
3         Yes          Yes  Don't know           No  ...  Don't know   
4          No          Yes          No          Yes  ...         Yes   

           leave mental_health_consequence phys_health_consequence  \
0  Somewhat easy                        No                      No   
1     Don't know                     Maybe                      No   
2      Very easy                        No                      No   
3     Don't know                     Maybe                      No   
4      Very easy                       Yes                     Yes   

      coworkers    supervisor mental_health_interview phys_health_interview  \
0           Yes           Yes                   Maybe                 Maybe   
1  Some of them           Yes                      No                 Maybe   
2           Yes           Yes                   Maybe                 Maybe   
3  Some of them            No                   Maybe                 Maybe   
4  Some of them  Some of them                      No                 Maybe   

  mental_vs_physical obs_consequence  
0         Don't know              No  
1         Don't know              No  
2         Don't know              No  
3         Don't know             Yes  
4                Yes             Yes  

[5 rows x 22 columns]

In [4]:
df.columns

Index(['Age', 'Gender', 'Country', 'self_employed', 'family_history',
       'no_employees', 'remote_work', 'tech_company', 'benefits',
       'care_options', 'wellness_program', 'seek_help', 'anonymity', 'leave',
       'mental_health_consequence', 'phys_health_consequence', 'coworkers',
       'supervisor', 'mental_health_interview', 'phys_health_interview',
       'mental_vs_physical', 'obs_consequence'],
      dtype='object')

In [5]:
# Gender
print(df['Gender'].unique())
df['Gender'].replace({'M':0, 'F':1}, inplace=True)
print(df['Gender'].unique())

['M' 'F']
[0 1]


In [6]:
# Country
mapping = {}
c = df['Country'].unique()
for i in range(len(c)):
    mapping[c[i]] = i
df['Country'].replace(mapping, inplace=True)

In [7]:
# Self employed
print(df['self_employed'].unique())
df['self_employed'].replace({'No':0, 'Yes':1}, inplace=True)
print(df['self_employed'].unique())

['No' 'Yes']
[0 1]


In [8]:
# Family history
print(df['family_history'].unique())
df['family_history'].replace({'No':0, 'Yes':1}, inplace=True)
print(df['family_history'].unique())

['Yes' 'No']
[1 0]


In [9]:
# No. of employees
print(df['no_employees'].unique())
df['no_employees'].replace({'1-5': 0, '6-25': 1, '26-100': 2, '100-500':3, '500-1000': 4, 'More than 1000':5}, inplace=True)
print(df['no_employees'].unique())

['6-25' '100-500' '26-100' '1-5' '500-1000' 'More than 1000']
[1 3 2 0 4 5]


In [10]:
# Remote work
print(df['remote_work'].unique())
df['remote_work'].replace({'No':0, 'Yes':1}, inplace=True)
print(df['remote_work'].unique())

['Yes' 'No']
[1 0]


In [11]:
# Tech company
print(df['tech_company'].unique())
df['tech_company'].replace({'No':0, 'Yes':1}, inplace=True)
print(df['tech_company'].unique())

['Yes' 'No']
[1 0]


In [12]:
# Benefits
print(df['benefits'].unique())
df['benefits'].replace({'No':0, 'Yes':1, "Don't know": 2}, inplace=True)
print(df['benefits'].unique())

['Yes' "Don't know" 'No']
[1 2 0]


In [13]:
# Care options
print(df['care_options'].unique())
df['care_options'].replace({'No':0, 'Yes':1, "Not sure": 2}, inplace=True)
print(df['care_options'].unique())

['Yes' 'No' 'Not sure']
[1 0 2]


In [14]:
# Wellness program
print(df['wellness_program'].unique())
df['wellness_program'].replace({'No':0, 'Yes':1, "Don't know": 2}, inplace=True)
print(df['wellness_program'].unique())

['No' 'Yes' "Don't know"]
[0 1 2]


In [15]:
# Seek help
print(df['seek_help'].unique())
df['seek_help'].replace({'No':0, 'Yes':1, "Don't know": 2}, inplace=True)
print(df['seek_help'].unique())

["Don't know" 'No' 'Yes']
[2 0 1]


In [16]:
df.columns

Index(['Age', 'Gender', 'Country', 'self_employed', 'family_history',
       'no_employees', 'remote_work', 'tech_company', 'benefits',
       'care_options', 'wellness_program', 'seek_help', 'anonymity', 'leave',
       'mental_health_consequence', 'phys_health_consequence', 'coworkers',
       'supervisor', 'mental_health_interview', 'phys_health_interview',
       'mental_vs_physical', 'obs_consequence'],
      dtype='object')

In [17]:
# Anonymity
print(df['anonymity'].unique())
df['anonymity'].replace({'No':0, 'Yes':1, "Don't know": 2}, inplace=True)
print(df['anonymity'].unique())

['Yes' "Don't know" 'No']
[1 2 0]


In [18]:
# Leave
print(df['leave'].unique())
df['leave'].replace({'Very easy':0, 'Somewhat easy':1, "Somewhat difficult":2,
                     "Very difficult":3, "Don't know": 4}, inplace=True)
print(df['leave'].unique())

['Somewhat easy' "Don't know" 'Very easy' 'Somewhat difficult'
 'Very difficult']
[1 4 0 2 3]


In [19]:
# Mental health consequence
print(df['mental_health_consequence'].unique())
df['mental_health_consequence'].replace({'No':0, 'Yes':1, "Maybe": 2}, inplace=True)
print(df['mental_health_consequence'].unique())

['No' 'Maybe' 'Yes']
[0 2 1]


In [20]:
# Physical Health Consequence
print(df['phys_health_consequence'].unique())
df['phys_health_consequence'].replace({'No':0, 'Yes':1, "Maybe": 2}, inplace=True)
print(df['phys_health_consequence'].unique())

['No' 'Yes' 'Maybe']
[0 1 2]


In [21]:
# Coworkers
print(df['coworkers'].unique())
df['coworkers'].replace({'No':0, 'Yes':1, "Some of them": 2}, inplace=True)
print(df['coworkers'].unique())

['Yes' 'Some of them' 'No']
[1 2 0]


In [22]:
# Superwiser
print(df['supervisor'].unique())
df['supervisor'].replace({'No':0, 'Yes':1, "Some of them": 2}, inplace=True)
print(df['supervisor'].unique())

['Yes' 'No' 'Some of them']
[1 0 2]


In [23]:
# Mental health interview
print(df['mental_health_interview'].unique())
df['mental_health_interview'].replace({'No':0, 'Yes':1, "Maybe": 2}, inplace=True)
print(df['mental_health_interview'].unique())

['Maybe' 'No' 'Yes']
[2 0 1]


In [24]:
# Physical health interview
print(df['phys_health_interview'].unique())
df['phys_health_interview'].replace({'No':0, 'Yes':1, "Maybe": 2}, inplace=True)
print(df['phys_health_interview'].unique())

['Maybe' 'No' 'Yes']
[2 0 1]


In [25]:
# Mental vs Physical
print(df['mental_vs_physical'].unique())
df['mental_vs_physical'].replace({'No':0, 'Yes':1, "Don't know": 2}, inplace=True)
print(df['mental_vs_physical'].unique())

["Don't know" 'Yes' 'No']
[2 1 0]


In [26]:
# Obs Consequences
print(df['obs_consequence'].unique())
df['obs_consequence'].replace({'No':0, 'Yes':1}, inplace=True)
print(df['obs_consequence'].unique())

['No' 'Yes']
[0 1]


In [27]:
df.head()

Age  Gender  Country  self_employed  family_history  no_employees  \
0   25       0        0              0               1             1   
1   42       0        0              0               1             1   
2   34       0        0              0               1             3   
3   26       1        0              0               0             2   
4   35       0        1              0               1             0   

   remote_work  tech_company  benefits  care_options  ...  anonymity  leave  \
0            1             1         1             1  ...          1      1   
1            1             1         2             0  ...          2      4   
2            0             1         1             1  ...          1      0   
3            1             1         2             0  ...          2      4   
4            0             1         0             1  ...          1      0   

   mental_health_consequence  phys_health_consequence  coworkers  supervisor  \
0                          0                        0          1           1   
1                          2                        0          2           1   
2                          0                        0          1           1   
3                          2                        0          2           0   
4                          1                        1          2           2   

   mental_health_interview  phys_health_interview  mental_vs_physical  \
0                        2                      2                   2   
1                        0                      2                   2   
2                        2                      2                   2   
3                        2                      2                   2   
4                        0                      2                   1   

   obs_consequence  
0                0  
1                0  
2                0  
3                1  
4                1  

[5 rows x 22 columns]

In [28]:
df.to_csv('test_cleaned_numericalised.csv', index=False)